### ISSUE TITLE
Database setup seems to be wrong

### ISSUE THREAD

**Issue by kayman-mk** [captn3m0/repology-dump-docker#1]
Interesting project!

I tried to use it with the repology webapp. But it didn't work. Seems that the database is not setup correctly.

1. The repology user is not allowed to access the tables
2. There is a problem with the character set. The webapp fails to convert unicode to ascii. May be we have to specify the character when creating the database?

**Comment by captn3m0** [comment]
I was merely using the dump for extracting data, not against the Webapp. It mostly follows the upstream configuration, so PRs would be welcome.
